// <auto-generated />
using System;
using LanzaTuIdea.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LanzaTuIdea.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250308120000_InitialAuthSchema")]
public partial class InitialAuthSchema
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.23")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("LanzaTuIdea.Api.Models.AppUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Codigo_Empleado")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("datetime2");

                b.Property<string>("NombreCompleto")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.HasIndex("UserName")
                    .IsUnique();

                b.ToTable("AppUsers");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.Employee", b =>
            {
                b.Property<string>("Codigo_Empleado")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Apellido1")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Apellido2")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Departamento")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("E_Mail")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Estatus")
                    .IsRequired()
                    .HasMaxLength(5)
                    .HasDefaultValue("A")
                    .HasColumnType("nvarchar(5)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Codigo_Empleado");

                b.ToTable("Employees");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.Idea", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AdminComment")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Clasificacion")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("CodigoEmpleado")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CreatedByUserId")
                    .HasColumnType("int");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Detalle")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Via")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.HasIndex("CreatedByUserId");

                b.ToTable("Ideas");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.IdeaHistory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("ChangedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("ChangedByUserId")
                    .HasColumnType("int");

                b.Property<string>("ChangeType")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("IdeaId")
                    .HasColumnType("int");

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.HasKey("Id");

                b.HasIndex("ChangedByUserId");

                b.HasIndex("IdeaId");

                b.ToTable("IdeaHistories");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Roles");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.UserRole", b =>
            {
                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.Property<int>("RoleId")
                    .HasColumnType("int");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("UserRoles");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.Idea", b =>
            {
                b.HasOne("LanzaTuIdea.Api.Models.AppUser", "CreatedByUser")
                    .WithMany("Ideas")
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CreatedByUser");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.IdeaHistory", b =>
            {
                b.HasOne("LanzaTuIdea.Api.Models.AppUser", "ChangedByUser")
                    .WithMany()
                    .HasForeignKey("ChangedByUserId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("LanzaTuIdea.Api.Models.Idea", "Idea")
                    .WithMany("History")
                    .HasForeignKey("IdeaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ChangedByUser");

                b.Navigation("Idea");
            });

        modelBuilder.Entity("LanzaTuIdea.Api.Models.UserRole", b =>
            {
                b.HasOne("LanzaTuIdea.Api.Models.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("LanzaTuIdea.Api.Models.AppUser", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });
    }
}
